### ISSUE TITLE
How do I supply broker basic authentication?

### ISSUE THREAD

**Issue by chookie** [DiUS/pact-provider-verifier-docker#8]
I have the below docker-compase.yml file which looks like trying to authentication with the broker to get the consumer.  I cannot find a sample of using authentication:

docker-compose
  ```
pactverifier:
    image: dius/pact-provider-verifier-docker
    depends_on:
    - api
    links:
    - api:api
    environment:
      provider: 'GraphQL-Test-Provider'
      provider_base_url: 'http://api:5000'
      pact_urls: 'http://x.x.x.x:1234'
      pact_broker_base_url: 'http://x.x.x.x:1234'
      broker_username: 'cli user'
      broker_password: 'cli password'
```

output
```
pactverifier_1  | WARN: the following non-mandatory environment variables have not been specified: '["provider_states_url", "provider_states_active_url"]'
api_1           | 🚀 GraphQL server ready at http://localhost:5000/graphql
pactverifier_1  | rake aborted!
pactverifier_1  | NoMethodError: undefined method `[]' for nil:NilClass
pactverifier_1  | /app/Rakefile:24:in `get_pact_consumer_name'
pactverifier_1  | /app/Rakefile:30:in `block (3 levels) in <top (required)>'
pactverifier_1  | /usr/local/bundle/gems/pact-provider-proxy-2.1.0/lib/pact/provider/proxy/tasks/proxy_verification_task.rb:12:in `initialize'
pactverifier_1  | /app/Rakefile:29:in `new'
pactverifier_1  | /app/Rakefile:29:in `block (2 levels) in <top (required)>'
pactverifier_1  | /app/Rakefile:28:in `each'
pactverifier_1  | /app/Rakefile:28:in `block in <top (required)>'
pactverifier_1  | /usr/local/bundle/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
pactverifier_1  | /usr/local/bin/bundle:23:in `load'
pactverifier_1  | /usr/local/bin/bundle:23:in `<main>'
pactverifier_1  | Tasks: TOP => verify_pacts
pactverifier_1  | (See full trace by running task with --trace)
graphql-test_pactverifier_1 exited with code 1
```
